version: '3'
services:
  client:
    image: drecoak/multi-client
    hostname: client
    mem_limit: 128m
    environment:
      - WDS_SOCKET_PORT=$WDS_SOCKET_PORT
  api:
    image: drecoak/multi-server
    hostname: api
    mem_limit: 128m
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: drecoak/multi-worker
    hostname: worker
    mem_limit: 128m
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    restart: always
    image: drecoak/multi-nginx
    hostname: nginx
    mem_limit: 128m
    ports:
      - '80:80'
