name: Client App Test
on:
  pull_request:
    branches:
      - main 
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Docker Login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build Docker Image
        run: docker build -t drecoak/client-test -f ./client/Dockerfile.dev ./client/
      - name: Run NPM Test
        run: docker run -e CI=true drecoak/client-test npm run test